Repository sunpy/ndcube, pull requests merged in 2020-10, with the labels that each got.

#287 Fix a bug in world_axis_coord_values when there is only one dimension in the WCS
  azure-pipelines.yml
  changelog/287.bugfix.rst
  ndcube/ndcube.py
  ndcube/tests/test_ndcube.py
  ndcube/tests/test_utils_wcs.py
Labels: ManualBackport

#293 Change name of NDCube.axis_world_coord_values
  changelog/293.bugfix.rst
  ndcube/ndcube.py
  ndcube/tests/test_ndcube.py
Labels: backport 1.3

#295 Add a cronjob to pipelines
  azure-pipelines.yml
Labels: No Changelog Entry Needed, backport 1.3, backport 1.4

#300 Remove pixel_to_world and world_to_pixel from NDCube
  changelog/300.removal.rst
  docs/ndcube.rst
  ndcube/ndcube.py
  ndcube/tests/test_ndcube.py
Labels: NDCube 2.0 MVP

#301 Add array_axis_physical_type properties to NDCubeSequence.
  changelog/301.feature.rst
  ndcube/ndcube_sequence.py
Labels: NDCube 2.0 MVP

#302 Remove NDCube.world_axis_physical_types.
  changelog/302.breaking.rst
  changelog/302.removal.rst
  docs/ndcollection.rst
  docs/ndcube.rst
  docs/ndcubesequence.rst
  ndcube/ndcollection.py
  ndcube/ndcube.py
  ndcube/ndcube_sequence.py
  ndcube/tests/helpers.py
  ndcube/tests/test_ndcollection.py
Labels: NDCube 2.0 MVP

#294 Change NDCubeSequence ImageAnimators parent class to ArrayAnimatorWCS.
  changelog/294.breaking.1.rst
  changelog/294.breaking.2.rst
  changelog/294.bugfix.rst
  ndcube/mixins/sequence_plotting.py
  ndcube/utils/wcs.py
Labels: ManualBackport, backport 1.4

#307 Fix sdist build of 1.4
  ndcube/visualization/__init__.py
Labels: No Changelog Entry Needed
