Repository sunpy/ndcube, pull requests merged in 2022-09, with the labels that each got.

#549 Update gallery example and prevent template from building
  examples/creating_ndcube_from_fitsfile.py
  examples/dev/example_template.py
Labels: No Changelog Entry Needed

#550 Prevent double CI on branch + PR
  .github/workflows/ci.yml
Labels: No Changelog Entry Needed

#552 Fix ndcube with reproject 0.9
  changelog/552.breaking.rst
  docs/conf.py
  ndcube/extra_coords/tests/test_extra_coords.py
  ndcube/ndcube.py
  ndcube/tests/test_ndcube.py
  ndcube/utils/wcs.py
  setup.cfg
Labels: [BugFix]

#551 Respect `plot_axes` when passing in `axes` when plotting 2D cubes
  changelog/551.bugfix.rst
  ndcube/visualization/mpl_plotter.py
  ndcube/visualization/tests/figure_hashes_mpl_352_ft_261_astropy_51_animators_100.json
  ndcube/visualization/tests/figure_hashes_mpl_352_ft_261_astropy_dev_animators_dev.json
  ndcube/visualization/tests/test_plotting.py
Labels: [BugFix], backport 2.0

#558 Fix internal imports to avoid weird circular import error
  ndcube/ndcube.py
  ndcube/ndcube_sequence.py
Labels: [BugFix], No Changelog Entry Needed, backport 2.0

#557 Backport PR #556 on branch 2.0 (Fix reusing the same axis in visualisation docs)
  docs/visualization.rst
Labels: No Changelog Entry Needed, backport 2.0

#559 Backport PR #558 on branch 2.0 (Fix internal imports to avoid weird circular import error)
  ndcube/ndcube.py
  ndcube/ndcube_sequence.py
Labels: [BugFix], No Changelog Entry Needed, backport 2.0

#561 Change the versions of figure test dependancies and use mpl dev
  ndcube/visualization/tests/figure_hashes_mpl_353_ft_261_astropy_504_animators_100.json
  ndcube/visualization/tests/figure_hashes_mpl_dev_ft_261_astropy_dev_animators_dev.json
  tox.ini
Labels: No Changelog Entry Needed, backport 2.0

#534 Add functools call to copy `plotter.plot` doc and signature to `plot`
  changelog/534.bugfix.rst
  ndcube/tests/test_ndcube.py
  ndcube/visualization/descriptor.py
Labels: [BugFix], backport 2.0

#563 Backport PR #534 on branch 2.0 (Add functools call to copy `plotter.plot` doc and signature to `plot`)
  changelog/534.bugfix.rst
  ndcube/tests/test_ndcube.py
  ndcube/visualization/descriptor.py
Labels: [BugFix], No Changelog Entry Needed, backport 2.0
