Repository sunpy/ndcube, pull requests merged in 2024-04, with the labels that each got.

#671 Backport PR #670 on branch 2.2 ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: No Changelog Entry Needed, backport 2.1, backport 2.2

#675 update dev figure hashes
  ndcube/visualization/tests/figure_hashes_mpl_dev_ft_261_astropy_dev_animators_dev.json
Labels: No Changelog Entry Needed, backport 2.2

#676 Backport PR #675 on branch 2.2 (update dev figure hashes)
  ndcube/visualization/tests/figure_hashes_mpl_dev_ft_261_astropy_dev_animators_dev.json
Labels: No Changelog Entry Needed, backport 2.2

#680 Fix ndcube ignore warnings to be sane again
  ndcube/conftest.py
  ndcube/ndcube.py
  ndcube/tests/test_ndcube.py
  pytest.ini
Labels: No Changelog Entry Needed, Run cron CI

#687 Make ndcube assert_cubes_equal function test metas are equal.
  ndcube/tests/helpers.py
Labels: No Changelog Entry Needed

#689 type(self).__name__
  ndcube/ndcube.py
Labels: No Changelog Entry Needed

#690 dev group for the lazy
  pyproject.toml
Labels: No Changelog Entry Needed

#692 Refactor method for producing new instance from arithmetic
  ndcube/ndcube.py
Labels: No Changelog Entry Needed

#694 Fix some issues in `NDCube.__init__`
  ndcube/ndcube.py
Labels: No Changelog Entry Needed

#693 Check more things in test helpers
  ndcube/tests/helpers.py
Labels: No Changelog Entry Needed
