Repository sunpy/ndcube, pull requests merged in 2024-12, with the labels that each got.

#788 Fixed a bug in NDCubeSequence.cube_like_dimensions.
  changelog/788.bugfix.rst
  ndcube/ndcube_sequence.py
  ndcube/tests/test_ndcubesequence.py
Labels: Minor Change

#780 Faster shortcut for working out coordinates values for non-correlated WCS
  changelog/780.bugfix.rst
  ndcube/conftest.py
  ndcube/ndcube.py
  ndcube/tests/test_ndcube.py
Labels: backport 2.2

#797 Add all to ensure that correct deps are used for source build
  .github/workflows/ci.yml
Labels: No Changelog Entry Needed, Run cron CI, Run publish, Minor Change
