Repository sunpy/ndcube, pull requests merged in 2025-05, with the labels that each got.

#834 Avoid using deprecated `astropy.utils.isiterable()`
  ndcube/extra_coords/table_coord.py
Labels: No Changelog Entry Needed, backport 2.3

#835 Backport PR #834 on branch 2.3 (Avoid using deprecated `astropy.utils.isiterable()`)
  ndcube/extra_coords/table_coord.py
Labels: No Changelog Entry Needed, backport 2.3

#838 Backport PR #837 on branch 2.3 (Update logo so white snake matches blue background)
  docs/logo/ndcube.pdf
  docs/logo/ndcube.png
  docs/logo/ndcube.svg
Labels: No Changelog Entry Needed, backport 2.3

#833 Remove physical-type equality check in reproject_to
  changelog/833.bugfix.rst
  ndcube/ndcube.py
Labels: backport 2.3

#839 Backport PR #833 on branch 2.3 (Remove physical-type equality check in reproject_to)
  changelog/833.bugfix.rst
  ndcube/ndcube.py
Labels: backport 2.3

#823 doc tweaks
  CHANGELOG.rst
  docs/nitpick-exceptions
  ndcube/ndcube.py
Labels: No Changelog Entry Needed, Documentation, Minor Change, backport 2.3

#843 [asdf] Add some documentation
  docs/conf.py
  docs/explaining_ndcube/asdf_serialization.rst
  docs/explaining_ndcube/index.rst
  ndcube/asdf/converters/tablecoord_converter.py
  ndcube/asdf/converters/tests/test_table_coordinate.py
  ndcube/asdf/entry_points.py
  ndcube/asdf/resources/manifests/ndcube-0.1.0.yaml
  ndcube/asdf/resources/schemas/multipletablecoordinate-1.0.0.yaml
  ndcube/conftest.py
  ndcube/extra_coords/table_coord.py
  ndcube/extra_coords/tests/test_lookup_table_coord.py
Labels: pre-commit.ci autofix
