Repository sunpy/ndcube, pull requests merged in 2025-06, with the labels that each got.

#849 Updates from package template
  .cruft.json
  .github/workflows/ci.yml
Labels: No Changelog Entry Needed, backport 2.3

#850 [2.3] Manual backports
  .cruft.json
  .github/workflows/ci.yml
  .pre-commit-config.yaml
Labels: No Changelog Entry Needed

#852 workaround for numpy checking string arrays found in sunraster
  ndcube/tests/helpers.py
Labels: No Changelog Entry Needed, Minor Change, backport 2.3

#854 Backport PR #802 on branch 2.3 (Skip plotting line data if it's all NaNs)
  changelog/802.trivial.rst
  ndcube/visualization/mpl_plotter.py
Labels: backport 2.3

#855 Too fast on merge
  ndcube/visualization/mpl_plotter.py
Labels: No Changelog Entry Needed, Minor Change, backport 2.3

#856 Backport PR #855 on branch 2.3 (Too fast on merge)
  ndcube/visualization/mpl_plotter.py
Labels: No Changelog Entry Needed, Minor Change, backport 2.3

#865 Make the numpy order explict in docstring for rebin + Fix Ci
  examples/dev/example_template.py
  ndcube/extra_coords/tests/test_extra_coords.py
  ndcube/ndcube.py
  ndcube/tests/test_ndcube_reproject_and_rebin.py
  ndcube/visualization/tests/figure_hashes_mpl_3100_ft_261_astropy_710_animators_124.json
  tox.ini
Labels: No Changelog Entry Needed, Minor Change, backport 2.3
