Repository sunpy/ndcube, pull requests merged in 2025-01, with the labels that each got.

#803 random test tweaks
  ndcube/extra_coords/tests/test_extra_coords.py
  ndcube/extra_coords/tests/test_lookup_table_coord.py
Labels: No Changelog Entry Needed

#806 Fix one test for new gwcs
  ndcube/extra_coords/tests/test_lookup_table_coord.py
Labels: No Changelog Entry Needed, backport 2.2

#807 Backport PR #806 on branch 2.2 (Fix one test for new gwcs)
  ndcube/extra_coords/tests/test_lookup_table_coord.py
Labels: No Changelog Entry Needed, backport 2.2

#808 More gwcs dev fixes
  docs/explaining_ndcube/tabular_coordinates.rst
  ndcube/extra_coords/table_coord.py
  ndcube/extra_coords/tests/test_lookup_table_coord.py
Labels: No Changelog Entry Needed

#809 Prepare for 2.3 Release
  .mailmap
  .zenodo.json
  CHANGELOG.rst
  RELEASE.rst
  changelog/455.feature.rst
  changelog/669.feature.rst
  changelog/677.feature.rst
  changelog/678.feature.rst
  changelog/684.breaking.rst
  changelog/684.feature.rst
  changelog/685.feature.rst
  changelog/691.doc.rst
  changelog/695.doc.rst
  changelog/705.trivial.rst
  changelog/729.trivial.rst
  changelog/732.feature.rst
  changelog/744.bugfix.rst
  changelog/767.feature.rst
  changelog/772.bugfix.rst
  changelog/777.feature.rst
  changelog/778.removal.rst
  changelog/788.bugfix.rst
  changelog/795.feature.rst
  changelog/798.bugfix.rst
Labels: No Changelog Entry Needed

#810 Update affiliation
  .zenodo.json
Labels: No Changelog Entry Needed

#813 Backport PR #812 on branch 2.3 (Updates from the package template)
  .cruft.json
  .pre-commit-config.yaml
  ndcube/utils/cube.py
Labels: No Changelog Entry Needed, backport 2.3
